public class Messages
{
    public static void main(String[] args)
    {
        // Your code here.
        // Create two Comment objects and print them out.
        // Then use the accessor methods to print out the instance variables
        Comment hello = new Comment("LeBron", "Hello", "January 1st, 2025");
        Comment goodbye = new Comment("LeBron", "Goodbye", "December 31st, 2025");
    }
}
